# Generated by Django 6.0 on 2026-01-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
