# Generated by Django 6.0 on 2026-01-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
