# Generated by Django 6.0 on 2026-01-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_session_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='paid_at',
        ),
    ]
