# Generated by Django 6.0 on 2026-10-06 11:23

from django.db import migrations, models


def preserve_historical_payments(apps, schema_editor):
    Session = apps.get_model('session', 'Session')
    Session.objects.filter(status__in=['waiting_payment', 'finished', 'paid']).update(status='stopped')
    Session.objects.filter(payment_done=True, paid_at__isnull=True).update(paid_at=models.F('end_time'))
    for session in Session.objects.select_related('table').all().iterator():
        if session.table_id:
            session.device_type = session.table.table_type
            session.device_name = f'PS {session.table.number - 6}' if session.device_type == 'PlayStation' else f'{session.table.number}-stol'
            session.save(update_fields=['device_type', 'device_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_remove_session_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='billing_type',
            field=models.CharField(choices=[('metered', 'Vaqt bo‘yicha'), ('prepaid', 'Oldindan to‘lov')], default='metered', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='prepaid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='session',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='device_type',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(preserve_historical_payments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
