# Generated by Django 6.0 on 2025-12-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemodel',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='tablemodel',
            name='position_y',
        ),
    ]
