# Generated by Django 6.0 on 2025-12-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tablemodel_position_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='tablemodel',
            name='number',
            field=models.PositiveIntegerField(default=3, unique=True),
            preserve_default=False,
        ),
    ]
