# Generated by Django 6.0 on 2025-12-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tablemodel_name_tablemodel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemodel',
            name='image',
        ),
    ]
