# Generated by Django 6.0 on 2026-01-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('table_type', models.CharField(choices=[('billiard', 'Billiard'), ('tennis', 'Tennis'), ('ps3', 'PlayStation 3')], default='billiard', max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
