# Generated by Django 6.0 on 2026-01-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
