# Generated by Django 6.0 on 2026-10-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_table_price_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Ichimliklar', max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='table',
            name='position_x',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='table',
            name='position_y',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='table',
            name='rotation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_type',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
