# Generated by Django 6.0 on 2026-10-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0010_pending_bar_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('starts_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='table.table')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
    ]
